title: "Ostrich AI"
logo: "/images/Nobg.png?raw=true"
description: >
  Data | People | Infra
  <br><br>
  Ready to shape the future of AI with Ostrich? 
  Click on  [Register Now](https://ostrich.thedatascienceguy.online/candidates) and become part of something extraordinary!
  <br><br>
  Corporate Office :-
  <br>
  308, Avior Corporate park,
  <br>
  L.B.S Marg, Mulund West,
  <br>
  Mumbai 400080
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
