title: "Ostrich AI"
logo: "/images/Circle.png?raw=true"
description: >
  Coming Soon
  <br>
  We're working hard to bring you something amazing. Stay tuned!
  <br>
  Corporate Office :-
  <br>
  308, Avior Corporate park,
  <br>
  L.B.S Marg, Mulund West,
  <br>
  Mumbai 400080
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
