title: "Ostrich AI"
logo: "/images/Nobg.png?raw=true"
description: >
  Data | People | Infra
  <br><br>
  Register for early Bird Access. We are working hard to bring you something awesome!
  <br><br>
  Communications Office:
  <br>
  308, Avior Corporate park,
  <br>
  L.B.S Marg, Mulund West,
  <br>
  Mumbai 400080
  <br><br>
  Regd. Office:
  <br>
  We Work Prestige Atlanta, 
  <br>
  Software Industry No 10/12, 
  <br>
  80 Feet Main Road, Koramangala, 1A Block,
  <br>
  Bangalore - 560034, Karnataka.
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
