title: "Ostrich AI"
logo: "/images/Nobg.png?raw=true"
description: >
  Data | People | Infra
  <br><br>
  Register for early Bird Access. We are working hard to bring you something awesome!
  <br><br>
  Corporate Office :-
  <br>
  308, Avior Corporate park,
  <br>
  L.B.S Marg, Mulund West,
  <br>
  Mumbai 400080
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
