title: "Ostrich AI"
logo: "/images/Nobg.png?raw=true"
description: >
  Data | People | Infra
  <br><br>
  Register for early Bird Access. We are working hard to bring you something awesome!
  <br><br>
  Regd. Office: 
  <br><br>
  We Work Prestige Atlanta,
  <br>
  80 Feet Main Road, Koramangala, 
  <br>
  1A Block, Bangalore - 560034.
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
