title: "Ostrich AI"
logo: "/images/Nobg.png?raw=true"
description: >
  Data | People | Infra
  <br><br>
  Register for early Bird Access. We are working hard to bring you something awesome!
  <br><br>
  <iframe
    title="DATA_BURROUGH checkout widget"
    src="https://nas.io/checkout-widget?communityCode=DATA_BURROUGH&communitySlug=%2Fostrich-ai&buttonText=Join%20as%20member&buttonTextColorHex=%23000&buttonBgColorHex=%2300e6e6&widgetTheme=dark&backgroundColorHex=%23000"
    width="100%"
    height="320"
    frameborder="0"
    referrerpolicy="no-referrer"
  ></iframe>
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
