title: "Ostrich AI"
logo: "/images/Circle.png?raw=true"
description: >
  We're working hard to bring you something amazing. Stay tuned!
  
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
